import type { ReactNode } from "react";

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section className="space-y-3 border-t py-8"><h2 className="text-2xl font-bold">{title}</h2><div className="space-y-3 leading-relaxed text-muted-foreground">{children}</div></section>;
}

export default function PrivacyPage() {
  return <div className="min-h-screen bg-background text-foreground">
    <header className="border-b"><div className="mx-auto flex max-w-3xl items-center justify-between gap-4 px-5 py-5"><a href="./" className="flex min-h-11 items-center gap-2 font-bold"><img src="./matlogg-logo.png" alt="" width="40" height="40" className="rounded-xl" />MatLogg</a><a href="./" className="btn-ghost">Til forsiden</a></div></header>
    <main id="main" className="mx-auto max-w-3xl px-5 py-12">
      <p className="eyebrow">Personvern</p><h1 className="mt-3 text-4xl font-bold tracking-tight">Personvernet ditt i MatLogg</h1>
      <p className="mt-4 text-muted-foreground">Sist oppdatert: 1. oktober 2026</p>
      <p className="my-8 leading-relaxed">Denne siden beskriver nettsiden og lokal bruk av appen slik den er under utvikling nå. Betapåmelding er ikke åpnet. Før konto, skysynk eller nye tjenester tas i bruk, oppdaterer vi informasjonen om den behandlingen.</p>
      <Section title="Hvem er ansvarlig?"><p>Nithusan Krishnasamymudali er ansvarlig for MatLogg og behandling av personopplysninger knyttet til nettsiden og henvendelser.</p><p>Kontakt: <a className="underline" href="mailto:nithusank.2002@gmail.com">nithusank.2002@gmail.com</a>. Unngå å sende matlogger, vekt eller andre helseopplysninger på vanlig e-post.</p></Section>
      <Section title="Når du besøker nettsiden"><p>Nettsiden har ingen analyseverktøy, reklamesporing, informasjonskapsler eller skjemaer som samler inn opplysninger. Knappen for betainteresse åpner bare informasjon; den registrerer deg ikke. Bilder fra appen viser fiktive demodata.</p><p>Siden leveres gjennom GitHub Pages. Ved lasting mottar vertstjenesten tekniske opplysninger som IP-adresse og informasjon om forespørselen. GitHub beskriver sin behandling, lagring og eventuelle overføringer utenfor EØS i <a className="underline" href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">sin personvernerklæring</a>. Vi har ikke et eget system for besøksstatistikk eller besøkslogger.</p></Section>
      <Section title="Hva appen lagrer lokalt"><p>Du kan bruke MatLogg uten konto. Matlogger, mengder, måltider, vannregistreringer, favoritter, lagrede måltider, skannehistorikk og innstillinger lagres på iPhonen. Personlige detaljer, mål og vekt lagres dersom du velger å registrere dem.</p><p>Opplysningene brukes til funksjonene du velger: logging, historikk, gjenbruk av måltider og oversikt. Vekt, mål og spisehistorikk kan være sensitive. Lokal logging lastes ikke automatisk opp; skysynk er deaktivert i den gjeldende versjonen. MatLogg tilbyr foreløpig ikke gjenoppretting eller synk mellom enheter.</p><p>Vi har ikke tilgang til matloggen som bare ligger på enheten din. Enhetens eventuelle sikkerhetskopier styres av dine Apple-/iOS-innstillinger.</p></Section>
      <Section title="Matsøk og eksterne oppslag"><p>Råvarene fra Matvaretabellen følger med appen og søkes lokalt. Ved et aktivt søk etter merkevarer eller skanning sendes søketeksten eller strekkoden til Open Food Facts for å hente produktinformasjon. Søketekst sendes ikke for hvert tastetrykk. Fra GS1 Data Matrix brukes bare produktnummeret; lotnummer og dato sendes ikke.</p><p>Open Food Facts mottar også vanlig tilkoblingsinformasjon, som IP-adresse og appidentifikasjon. Selve matloggen, vekten og målene følger ikke med disse oppslagene. Se <a className="underline" href="https://world.openfoodfacts.org/privacy">Open Food Facts sin personvernerklæring</a>. Produktdata kan mellomlagres lokalt for raskere oppslag.</p></Section>
      <Section title="Kamera, bilder og analyse"><p>Kameraet brukes når du starter skanning eller tar et produktbilde, etter iOS sin tillatelse. Du kan også velge ett bilde med systemets bildevelger. Produktbilder lagres lokalt, uten original fotometadata, og lastes ikke opp eller synkroniseres.</p><p>Det er ikke koblet inn et SDK for bruksanalyse eller krasjrapportering i den gjeldende appversjonen. Eventuelle valg i appen betyr derfor ikke at slike data sendes nå. Vi selger ikke personopplysninger og bruker dem ikke til annonsesporing.</p></Section>
      <Section title="Henvendelser, formål og behandlingsgrunnlag"><p>Hvis du kontakter oss, behandler vi e-postadresse og innholdet du sender for å svare og følge opp saken. Grunnlaget er vår berettigede interesse i å håndtere spørsmål om MatLogg (GDPR artikkel 6 nr. 1 bokstav f). Henvendelser om å inngå en avtale kan behandles for å gjennomføre tiltak på din forespørsel (bokstav b).</p><p>Vi ber ikke om helseopplysninger i henvendelser. Opplysninger som ikke trengs for oppfølging, skal fjernes. Korrespondanse beholdes bare så lenge den er nødvendig for å følge opp henvendelsen eller håndtere en konkret rettslig plikt eller pågående tvist.</p></Section>
      <Section title="Lagring, sletting og eksport"><p>Lokale appdata blir liggende til du sletter dem. Under Profil → Innstillinger kan du laste ned dataene dine. For å fjerne appens lokale lagring fra iPhonen kan du slette appen i iOS; «Avlast app» beholder dataene og er ikke det samme som sletting. Eksporterte filer og sikkerhetskopier du selv har opprettet, må slettes separat.</p><p>Ved lokal bruk uten konto har vi ingen serverkopi å hente ut eller slette. Konto- og serversletting vil bli beskrevet særskilt før slike tjenester åpnes.</p></Section>
      <Section title="Rettighetene dine"><p>For personopplysninger vi behandler, kan du be om innsyn, retting, sletting og begrensning. Du kan protestere mot behandling basert på berettiget interesse og ha rett til dataportabilitet når vilkårene gjelder. Dersom en fremtidig funksjon bygger på samtykke, kan samtykket trekkes tilbake.</p><p>Send forespørselen til kontaktadressen over. Vi svarer normalt innen én måned og kan be om nødvendig bekreftelse på identiteten din. Du kan klage til <a className="underline" href="https://www.datatilsynet.no/">Datatilsynet</a>.</p></Section>
      <Section title="Endringer"><p>Datoen øverst viser når teksten sist ble oppdatert. Vesentlige endringer i behandling av personopplysninger varsles før de trer i kraft, og nødvendige valg eller samtykker innhentes før nye funksjoner aktiveres.</p></Section>
    </main>
  </div>;
}
