import type { ReactNode } from "react";

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section className="space-y-3 border-t py-8"><h2 className="text-2xl font-bold">{title}</h2><div className="space-y-3 leading-relaxed text-muted-foreground">{children}</div></section>;
}

export default function PrivacyPage() {
  return <div className="min-h-screen bg-background text-foreground">
    <header className="border-b"><div className="mx-auto flex max-w-3xl items-center justify-between gap-4 px-5 py-5"><a href="./" className="flex min-h-11 items-center gap-2 font-bold"><img src="./matlogg-logo.png" alt="" width="40" height="40" className="rounded-xl" />MatLogg</a><a href="./" className="btn-ghost">Til forsiden</a></div></header>
    <main id="main" className="mx-auto max-w-3xl px-5 py-12">
      <p className="eyebrow">Personvern</p><h1 className="mt-3 text-4xl font-bold tracking-tight">Personvernet ditt i MatLogg</h1>
      <p className="mt-4 text-muted-foreground">Sist oppdatert: 8. oktober 2026</p>
      <p className="my-8 leading-relaxed">Denne siden beskriver nettsiden, lokal bruk av appen og valgfri konto. Betapåmelding er ikke åpnet. Skysynk og gjenoppretting mellom enheter er ikke tilgjengelig. Før nye tjenester tas i bruk, oppdaterer vi informasjonen om behandlingen.</p>
      <Section title="Hvem er ansvarlig?"><p>Nithusan Krishnasamymudali er behandlingsansvarlig for MatLogg, inkludert konto, nettsiden og henvendelser.</p><p>Kontakt: <a className="underline" href="mailto:nithusank.2002@gmail.com">nithusank.2002@gmail.com</a>. Unngå å sende matlogger, vekt eller andre helseopplysninger på vanlig e-post.</p></Section>
      <Section title="Når du besøker nettsiden"><p>Nettsiden har ingen analyseverktøy, reklamesporing, informasjonskapsler eller skjemaer som samler inn opplysninger. Det er ingen betapåmelding på siden. Demoens knapper bytter bare mellom appbilder; de registrerer ingen mat eller opplysninger. Bilder fra appen viser fiktive demodata.</p><p>Siden leveres gjennom GitHub Pages. Ved lasting mottar vertstjenesten tekniske opplysninger som IP-adresse og informasjon om forespørselen. GitHub beskriver sin behandling, lagring og eventuelle overføringer utenfor EØS i <a className="underline" href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">sin personvernerklæring</a>. Vi har ikke et eget system for besøksstatistikk eller besøkslogger.</p></Section>
      <Section title="Hva appen lagrer lokalt"><p>Du kan bruke MatLogg uten konto. Matlogger, mengder, måltider, vannregistreringer, favoritter, lagrede måltider, skannehistorikk og innstillinger lagres på iPhonen. Personlige detaljer, mål og vekt lagres dersom du velger å registrere dem. Fødselsdato er påkrevd dersom du velger å lagre Personlige detaljer i dagens appversjon; øvrige felt er valgfrie.</p><p>Opplysningene brukes til funksjonene du velger: logging, historikk, gjenbruk av måltider og oversikt. Vekt, mål og spisehistorikk kan være sensitive. Lokal logging lastes ikke automatisk opp; skysynk er deaktivert i den gjeldende versjonen. MatLogg tilbyr foreløpig ikke gjenoppretting eller synk mellom enheter.</p><p>Vi har ikke tilgang til matloggen som bare ligger på enheten din. Enhetens eventuelle sikkerhetskopier styres av dine Apple-/iOS-innstillinger.</p></Section>
      <Section title="Valgfri konto og innlogging"><p>MatLogg kan brukes uten konto. Hvis du oppretter konto med e-post og passord eller logger inn med Apple, bruker vi Supabase Auth til å håndtere e-postadresse, bruker-ID, innloggingsidentitet og sikker passordhåndtering. Vi mottar ikke Apple-passordet ditt og lagrer ikke passord i klartekst. Supabase brukes som databehandler for konto og autentisering.</p><p>Konto og autentisering behandles for å levere tjenesten (GDPR artikkel 6 nr. 1 bokstav b). En konto gir foreløpig ikke skybackup av matlogger, mål, vekt eller bilder. Et valgfritt visningsnavn og navn du deler med Apple, håndteres lokalt i appen; MatLogg sender ikke Apple-navnet til Supabase.</p><p>Skysynk av helseopplysninger er deaktivert. Før slik opplasting åpnes, må grunnlaget etter både artikkel 6 og artikkel 9 være avklart og dokumentert. Nødvendige valg eller uttrykkelig samtykke skal innhentes før opplasting dersom samtykke brukes.</p></Section>
      <Section title="Matsøk og eksterne oppslag"><p>Råvarene fra Matvaretabellen følger med appen og søkes lokalt. Ved et aktivt søk etter merkevarer eller skanning sendes søketeksten eller strekkoden til Open Food Facts for å hente produktinformasjon. Søketekst sendes ikke for hvert tastetrykk. Fra GS1 Data Matrix brukes bare produktnummeret; lotnummer og dato sendes ikke.</p><p>Open Food Facts mottar også vanlig tilkoblingsinformasjon, som IP-adresse og appidentifikasjon. Selve matloggen, vekten og målene følger ikke med disse oppslagene. Se <a className="underline" href="https://world.openfoodfacts.org/privacy">Open Food Facts sin personvernerklæring</a>. Produktdata kan mellomlagres lokalt for raskere oppslag.</p></Section>
      <Section title="Kamera, bilder og analyse"><p>Kameraet brukes når du starter skanning eller tar et produktbilde, etter iOS sin tillatelse. Du kan også velge ett bilde med systemets bildevelger. Produktbilder lagres lokalt, uten original fotometadata, og lastes ikke opp eller synkroniseres.</p><p>Det er ikke koblet inn et SDK for bruksanalyse eller krasjrapportering i den gjeldende appversjonen. Eventuelle valg i appen betyr derfor ikke at slike data sendes nå. Vi selger ikke personopplysninger og bruker dem ikke til annonsesporing.</p></Section>
      <Section title="Henvendelser, formål og behandlingsgrunnlag"><p>Hvis du kontakter oss, behandler vi e-postadresse og innholdet du sender for å svare og følge opp saken. Grunnlaget er vår berettigede interesse i å håndtere spørsmål om MatLogg (GDPR artikkel 6 nr. 1 bokstav f). Henvendelser om å inngå en avtale kan behandles for å gjennomføre tiltak på din forespørsel (bokstav b).</p><p>Vi ber ikke om helseopplysninger i henvendelser. Opplysninger som ikke trengs for oppfølging, skal fjernes. Korrespondanse beholdes bare så lenge den er nødvendig for å følge opp henvendelsen eller håndtere en konkret rettslig plikt eller pågående tvist.</p></Section>
      <Section title="Lagring, sletting og eksport"><p>Lokale appdata blir liggende til du sletter dem. Under Profil → Innstillinger kan du eksportere data for den aktive profilen. Uten konto velger du «Slett alle lokale data» for å fjerne logger, mål, bilder og personlige detaljer for profilen. Med konto betyr «Fjern lokale data» at data bare fjernes fra denne iPhonen; serverkontoen slettes ikke.</p><p>«Slett konto» sender en forespørsel til serveren. Når serveren bekrefter forespørselen, sperres innlogging, og lokale profildata fjernes. Serverkontoen og tilknyttede data, inkludert egne serverprodukter, forsøkes slettet permanent i samme forespørsel, uten fast ventetid. Ved tekniske feil prøver en slettejobb igjen hvert femte minutt. Bekreftet lokal opprydding som avbrytes, forsøkes igjen ved neste oppstart og kan fullføres fra velkomstskjermen uten innlogging.</p><p>Hvis serversvaret uteblir, kan kontostatus være usikker. Lokal sletting alene bekrefter ikke serversletting; kontakt oss for å kontrollere status. Ved lokal bruk uten konto har vi ingen serverkopi av matloggen å hente ut eller slette.</p><p>Eksporterte filer du selv har lagret eller delt, og enhetens sikkerhetskopier, må håndteres separat. Du kan også fjerne appens lokale lagring ved å slette appen i iOS; «Avlast app» beholder dataene. Sletting fra aktive serverdatabaser innebærer ikke nødvendigvis umiddelbar fysisk fjerning fra leverandørens sikkerhetskopier. Slike kopier skal være tilgangsbegrenset, utløpe etter fastsatt lagringstid, og tidligere slettinger skal gjenanvendes før en gjenopprettet database tas i bruk.</p></Section>
      <Section title="Rettighetene dine"><p>For personopplysninger vi behandler, kan du be om innsyn, retting, sletting og begrensning. Du kan protestere mot behandling basert på berettiget interesse og ha rett til dataportabilitet når vilkårene gjelder. Dersom en fremtidig funksjon bygger på samtykke, kan samtykket trekkes tilbake.</p><p>Send forespørselen til kontaktadressen over. Vi svarer normalt innen én måned og kan be om nødvendig bekreftelse på identiteten din. Du kan klage til <a className="underline" href="https://www.datatilsynet.no/">Datatilsynet</a>.</p></Section>
      <section id="bildekilder" className="space-y-3 border-t py-8">
        <h2 className="text-2xl font-bold">Bildekilder og lisenser</h2>
        <div className="space-y-3 leading-relaxed text-muted-foreground">
          <p>Appbildene er tatt i MatLogg med fiktive demodata. Produktfotografiene som vises inne i appbildene, kommer fra Open Food Facts-bidragsytere og er tilgjengelige under <a className="underline" href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. De er gjengitt som del av appens brukergrensesnitt og skalert sammen med skjermbildene. Lisensen gjelder produktfotografiene, ikke automatisk hele MatLogg-nettsiden.</p>
          <p>Produktdata kommer fra Open Food Facts-bidragsytere under <a className="underline" href="https://opendatacommons.org/licenses/odbl/1-0/">Open Database License (ODbL)</a>. Se også <a className="underline" href="https://world.openfoodfacts.org/terms-of-use">vilkårene for gjenbruk</a>. Råvaredata i appen kommer fra Matvaretabellen.</p>
          <p>Produktkilder for demomaterialet:</p>
          <ul className="list-disc space-y-2 pl-5">
          <li><a className="underline" href="https://world.openfoodfacts.org/product/7044416013141">Lettkokte havregryn (AXA Bjørn)</a></li>
          <li><a className="underline" href="https://world.openfoodfacts.org/product/7300400129459">Knekkebrød Runde Sesam & Havsalt (Wasa)</a></li>
          <li><a className="underline" href="https://world.openfoodfacts.org/product/7038010053368">Gulost (TINE)</a></li>
          <li><a className="underline" href="https://world.openfoodfacts.org/product/7039010016322">Makrell i tomat (Stabburet)</a></li>
          <li><a className="underline" href="https://world.openfoodfacts.org/product/7036110008844">Peanøttsmør (Mills)</a></li>
          <li><a className="underline" href="https://world.openfoodfacts.org/product/7038010054471">Cottage Cheese Original 4,3% fett (TINE)</a></li>
          <li><a className="underline" href="https://world.openfoodfacts.org/product/7622210816672">Kvikk Lunsj (Freia)</a></li>
          </ul>
          <p><a className="underline" href="./bildekilder.txt">Full kildeoversikt med lenker til originalfotografiene</a>.</p>
          <p>De store bildene av yoghurt med havre og bær og laks med poteter er AI-genererte illustrasjoner laget for MatLogg. De er ikke produktfotografier eller dokumentasjon av næringsinnhold. Merkenavn og varemerker tilhører sine respektive eiere; visningen innebærer ikke samarbeid eller anbefaling fra produsentene.</p>
        </div>
      </section>
      <Section title="Endringer"><p>Datoen øverst viser når teksten sist ble oppdatert. Vesentlige endringer i behandling av personopplysninger varsles før de trer i kraft, og nødvendige valg eller samtykker innhentes før nye funksjoner aktiveres.</p></Section>
    </main>
  </div>;
}
